import os
os.chdir(<file_location>)
for f in os.listdir():
    print(f) # this will print the names of all the files in the current directory
    f_name, f_ext = os.path.splitext(f)
    f_title, f_type, f_text, f_num = f_name.split('-') # this will split the name of the file into four parts using the hyphen as a separator and assign them to the variables f_title, f_type, f_text, f_num
    f_title = f_title.strip()[1:] # this will remove any leading or trailing whitespace from the title of the file
    f_type = f_type.strip() # this will remove any leading or trailing whitespace from the type of the file
    f_text = f_text.strip() # this will remove any leading or trailing whitespace from the text of the file
    f_num = f_num.strip() # this will remove any leading or trailing whitespace from the number of the file
    f_num = f_num.zfill(2)
    rename = f"{f_num}-{f_text}{f_ext}"
    print(rename)
    os.rename(f, rename)

# this will rename the files in the current directory to the new names generated by the code above